name: lint

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  lint-readme:
    name: readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cloudposse/build-harness@0.39.0
        with:
          entrypoint: /usr/bin/make
          args: readme/lint
